In [1]:
import pandas as pd
books = pd.read_csv("books_with_categories.csv")

In [3]:
from transformers import pipeline
classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device =-1,
                      return_all_scores=True)
classifier("I love this!")

C:\Users\oluok\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
C:\Users\oluok\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\oluok\.cache\huggingface\hub\models--j-hartmann--emotion-english-distilroberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 16071.30it/s]
RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528691716492176},
  {'label': 'neutral', 'score': 0.005764589179307222},
  {'label': 'anger', 'score': 0.004419787786900997},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.001611991785466671},
  {'label': 'fear', 'score': 0.0004138525982853025}]]

In [4]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [5]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.654840350151062},
  {'label': 'neutral', 'score': 0.1698523312807083},
  {'label': 'sadness', 'score': 0.11640936881303787},
  {'label': 'surprise', 'score': 0.020700648427009583},
  {'label': 'disgust', 'score': 0.01910071074962616},
  {'label': 'joy', 'score': 0.015161431394517422},
  {'label': 'anger', 'score': 0.003935148473829031}]]

In [6]:
classifier(books["description"][0].split('.'))

[[{'label': 'surprise', 'score': 0.7296019792556763},
  {'label': 'neutral', 'score': 0.14038611948490143},
  {'label': 'fear', 'score': 0.06816229224205017},
  {'label': 'joy', 'score': 0.04794260114431381},
  {'label': 'anger', 'score': 0.009156369604170322},
  {'label': 'disgust', 'score': 0.0026284789200872183},
  {'label': 'sadness', 'score': 0.002122164238244295}],
 [{'label': 'neutral', 'score': 0.4493708610534668},
  {'label': 'disgust', 'score': 0.2735908627510071},
  {'label': 'joy', 'score': 0.10908335447311401},
  {'label': 'sadness', 'score': 0.09362750500440598},
  {'label': 'anger', 'score': 0.04047826677560806},
  {'label': 'surprise', 'score': 0.026970183476805687},
  {'label': 'fear', 'score': 0.006879056338220835}],
 [{'label': 'neutral', 'score': 0.6462154388427734},
  {'label': 'sadness', 'score': 0.24273377656936646},
  {'label': 'disgust', 'score': 0.04342271387577057},
  {'label': 'surprise', 'score': 0.028300553560256958},
  {'label': 'joy', 'score': 0.014211496338248253},
  {'label': 'fear', 'score': 0.01408410258591175},
  {'label': 'anger', 'score': 0.011031907983124256}],
 [{'label': 'fear', 'score': 0.9281682968139648},
  {'label': 'anger', 'score': 0.03219083696603775},
  {'label': 'neutral', 'score': 0.012808673083782196},
  {'label': 'sadness', 'score': 0.008756859228014946},
  {'label': 'surprise', 'score': 0.008597901090979576},
  {'label': 'disgust', 'score': 0.008431811816990376},
  {'label': 'joy', 'score': 0.0010455823503434658}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104127116501331},
  {'label': 'disgust', 'score': 0.006480586249381304},
  {'label': 'fear', 'score': 0.005393980070948601},
  {'label': 'surprise', 'score': 0.0022869384847581387},
  {'label': 'anger', 'score': 0.001842886907979846},
  {'label': 'joy', 'score': 0.0017338756006211042}],
 [{'label': 'joy', 'score': 0.9327981472015381},
  {'label': 'disgust', 'score': 0.03771701827645302},
  {'label': 'neutral', 'score': 0.015891805291175842},
  {'label': 'sadness', 'score': 0.006444500293582678},
  {'label': 'anger', 'score': 0.005024965852499008},
  {'label': 'surprise', 'score': 0.001581205171532929},
  {'label': 'fear', 'score': 0.0005423059337772429}],
 [{'label': 'joy', 'score': 0.6528709530830383},
  {'label': 'neutral', 'score': 0.2542746365070343},
  {'label': 'surprise', 'score': 0.06808288395404816},
  {'label': 'sadness', 'score': 0.009908979758620262},
  {'label': 'disgust', 'score': 0.006512224208563566},
  {'label': 'anger', 'score': 0.004821305628865957},
  {'label': 'fear', 'score': 0.003529016626998782}],
 [{'label': 'neutral', 'score': 0.5494766235351562},
  {'label': 'sadness', 'score': 0.11169016361236572},
  {'label': 'disgust', 'score': 0.10400673002004623},
  {'label': 'surprise', 'score': 0.07876551896333694},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136285349726677},
  {'label': 'joy', 'score': 0.040564440190792084}]]

In [7]:
sentences=books["description"][0].split('.')
predictions=classifier(sentences)

In [8]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [9]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296019792556763},
 {'label': 'neutral', 'score': 0.14038611948490143},
 {'label': 'fear', 'score': 0.06816229224205017},
 {'label': 'joy', 'score': 0.04794260114431381},
 {'label': 'anger', 'score': 0.009156369604170322},
 {'label': 'disgust', 'score': 0.0026284789200872183},
 {'label': 'sadness', 'score': 0.002122164238244295}]

In [10]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [11]:
predictions[3]

[{'label': 'fear', 'score': 0.9281682968139648},
 {'label': 'anger', 'score': 0.03219083696603775},
 {'label': 'neutral', 'score': 0.012808673083782196},
 {'label': 'sadness', 'score': 0.008756859228014946},
 {'label': 'surprise', 'score': 0.008597901090979576},
 {'label': 'disgust', 'score': 0.008431811816990376},
 {'label': 'joy', 'score': 0.0010455823503434658}]

In [13]:
sorted(predictions[0],key=lambda x: x['label'])

[{'label': 'anger', 'score': 0.009156369604170322},
 {'label': 'disgust', 'score': 0.0026284789200872183},
 {'label': 'fear', 'score': 0.06816229224205017},
 {'label': 'joy', 'score': 0.04794260114431381},
 {'label': 'neutral', 'score': 0.14038611948490143},
 {'label': 'sadness', 'score': 0.002122164238244295},
 {'label': 'surprise', 'score': 0.7296019792556763}]

In [16]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbns = []
emotion_scores_list = []

def calculate_emotion_scores(predictions, strategy="mean"):

    per_emotion_scores = {label: [] for label in emotion_labels}

    for prediction in predictions:
        for item in prediction:
            label = item["label"].lower()
            if label in per_emotion_scores:
                per_emotion_scores[label].append(item["score"])
    if strategy == "mean":
        return {label: np.mean(scores) if scores else 0.0
                for label, scores in per_emotion_scores.items()}
    else:
        return {label: np.max(scores) if scores else 0.0
                for label, scores in per_emotion_scores.items()}

In [19]:
isbns = []
emotion_scores= {label: [] for label in emotion_labels}

for i in range(10):
    isbns.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [20]:
emotion_scores

{'anger': [np.float64(0.021085026703076437),
  np.float64(0.08872448103502392),
  np.float64(0.039533889231582485),
  np.float64(0.10958827030844986),
  np.float64(0.04434010739039097),
  np.float64(0.1301859114319086),
  np.float64(0.11615163722837513),
  np.float64(0.030368404928594828),
  np.float64(0.12057161595051487),
  np.float64(0.029636319261044264)],
 'disgust': [np.float64(0.06034880326478742),
  np.float64(0.07088202892336995),
  np.float64(0.04336954424312959),
  np.float64(0.07961062405956909),
  np.float64(0.08300445800913232),
  np.float64(0.34513009153306484),
  np.float64(0.05647666521624408),
  np.float64(0.05007615716507038),
  np.float64(0.1139889919043829),
  np.float64(0.09646206845839818)],
 'fear': [np.float64(0.13476523801364237),
  np.float64(0.17272920069517567),
  np.float64(0.3759148232638836),
  np.float64(0.10391972991055809),
  np.float64(0.034571839696062465),
  np.float64(0.030926765874028206),
  np.float64(0.1936370637267828),
  np.float64(0.17755387350916862),
  np.float64(0.23060723145802817),
  np.float64(0.03514499900241693)],
 'joy': [np.float64(0.22503130629775114),
  np.float64(0.10825258966069669),
  np.float64(0.2700908422314872),
  np.float64(0.11435644229641184),
  np.float64(0.024379915158663477),
  np.float64(0.021407045031082816),
  np.float64(0.09386656437577172),
  np.float64(0.019021695014089346),
  np.float64(0.012955784215591848),
  np.float64(0.02971525490283966)],
 'sadness': [np.float64(0.18030518642626703),
  np.float64(0.042325270781293514),
  np.float64(0.041283561498858035),
  np.float64(0.04654848825884983),
  np.float64(0.144528987418328),
  np.float64(0.05657164182048291),
  np.float64(0.10673061902211471),
  np.float64(0.318233090142409),
  np.float64(0.16996101817737022),
  np.float64(0.05786041542887688)],
 'surprise': [np.float64(0.11802339549467433),
  np.float64(0.0954519972205162),
  np.float64(0.031042587167272966),
  np.float64(0.029754986171610653),
  np.float64(0.04617345060354897),
  np.float64(0.09005328570492566),
  np.float64(0.040594480762427505),
  np.float64(0.10904692610104878),
  np.float64(0.055040851972686745),
  np.float64(0.06042910863955816)],
 'neutral': [np.float64(0.26044103561434895),
  np.float64(0.42163445064798),
  np.float64(0.19876477619012198),
  np.float64(0.5162214916199446),
  np.float64(0.6230012348720005),
  np.float64(0.32572528161108494),
  np.float64(0.39254298128864984),
  np.float64(0.2956998310983181),
  np.float64(0.29687446759392816),
  np.float64(0.690751830736796)]}

In [29]:
from tqdm import tqdm
import pandas as pd

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbns = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbns.append(books["isbn13"].iloc[i])

    description = books["description"].iloc[i]

    if pd.isna(description):
        for label in emotion_labels:
            emotion_scores[label].append(0.0)
        continue

    sentences = [s.strip() for s in description.split(".") if s.strip()]
    predictions = classifier(sentences)
    scores = calculate_emotion_scores(predictions, strategy="max")

    for label in emotion_labels:
        emotion_scores[label].append(scores[label])

emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbns

100%|██████████| 5197/5197 [23:13<00:00,  3.73it/s]

In [30]:
import pandas as pd
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbns

In [31]:
emotions_df.head()

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.029641,0.338238,0.983973,0.949028,0.956065,0.729602,0.697846,9780002005883
1,0.594468,0.461991,0.935215,0.704422,0.051413,0.212222,0.891110,9780002261982
2,0.041301,0.024568,0.973285,0.767238,0.010860,0.009796,0.042176,9780006178736
3,0.325306,0.125763,0.436338,0.242209,0.043272,0.029084,0.732685,9780006280897
4,0.091732,0.197434,0.095043,0.041146,0.475880,0.074878,0.890048,9780006280934

In [37]:
books = pd.merge(books,emotions_df, on="isbn13")

In [38]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,sadness_y,surprise_y,neutral_y,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,0.956065,0.729602,0.697846,0.029641,0.338238,0.983973,0.949028,0.956065,0.729602,0.697846
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.051413,0.212222,0.891110,0.594468,0.461991,0.935215,0.704422,0.051413,0.212222,0.891110
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,0.010860,0.009796,0.042176,0.041301,0.024568,0.973285,0.767238,0.010860,0.009796,0.042176
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,0.043272,0.029084,0.732685,0.325306,0.125763,0.436338,0.242209,0.043272,0.029084,0.732685
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,0.475880,0.074878,0.890048,0.091732,0.197434,0.095043,0.041146,0.475880,0.074878,0.890048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,0.974265,0.028640,0.807057,0.204142,0.053939,0.923713,0.303278,0.974265,0.028640,0.807057
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,0.016014,0.227765,0.891073,0.058450,0.127941,0.025688,0.400263,0.016014,0.227765,0.891073
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.060436,0.056820,0.344736,0.011246,0.010868,0.314811,0.942169,0.060436,0.056820,0.344736
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,0.317455,0.049227,0.950763,0.034505,0.080506,0.409872,0.776052,0.317455,0.049227,0.950763
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,0.017871,0.028612,0.920466,0.017204,0.062639,0.024447,0.958549,0.017871,0.028612,0.920466

In [36]:
books.to_csv("Real_books.csv", index=False)

In [39]:
cols_to_drop = [col for col in books.columns if col.endswith("_x") or col.endswith("_y")]
books = books.drop(columns=cols_to_drop)

books.to_csv("Real_books.csv", index=False)